name: Test Github Action
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make
      - name: Commit y Push el pdf
          run: |
            git config user.name <username>
            git config user.email <email>
            git add .
            git commit -m "add: pdf compilado"
            git push
